facebook:
  wait-for-render-url: 4000
  wait-for-click: 2000
  nro-execucoes-ver-mais: 10
  xpathExpression-link-ver-mais: //span[contains(text(), 'Ver mais ')] #Array.from(document.querySelectorAll('span')).find(el => el.textContent.contains('Ver mais ')).click()
  xpathExpression-link-respostas: //span[contains(text(), ' respostas')]
  xpathExpression-div-comentarioCompleto: //div[@class="x1r8uery x1iyjqo2 x6ikm8r x10wlt62 x1pi30zi"]
